/**
 * Expert community knowledge base for Dubai villa communities.
 * Prioritized: Emirates Living cluster, Jumeirah Park, Arabian Ranches.
 *
 * Figures are typical market benchmarks sourced from public reports
 * (Property Monitor, DXB Interact, Bayut/PropertyFinder trends, DLD
 * transaction data). Refresh via /api/market/refresh cron.
 */

export interface SeedCommunity {
  slug: string;
  name: string;
  tier: "priority" | "premium" | "standard";
  propertyTypes: string[];
  developer?: string;
  handover?: string;
  avgPricePerSqft: number;
  avgYield: number;
  minPrice: number;
  maxPrice: number;
  amenities: string[];
  description: string;
}

export const SEED_COMMUNITIES: SeedCommunity[] = [
  // ===== PRIORITY: Emirates Living =====
  {
    slug: "the-springs",
    name: "The Springs",
    tier: "priority",
    propertyTypes: ["Villa", "Townhouse"],
    developer: "Emaar",
    handover: "2003-2007",
    avgPricePerSqft: 1400,
    avgYield: 5.8,
    minPrice: 2800000,
    maxPrice: 6500000,
    amenities: ["Lakes", "Community pools", "Retail", "Schools nearby", "Jogging tracks"],
    description: "Family-friendly gated community in Emirates Living. Lakeside 2-4BR townhouses. Strong secondary-market turnover, consistent 5.5-6% yields, mature landscaping.",
  },
  {
    slug: "the-meadows",
    name: "The Meadows",
    tier: "priority",
    propertyTypes: ["Villa"],
    developer: "Emaar",
    handover: "2004-2008",
    avgPricePerSqft: 1650,
    avgYield: 5.2,
    minPrice: 5500000,
    maxPrice: 22000000,
    amenities: ["Meadows Village", "Lakes", "Schools", "Tennis courts", "Landscaped parks"],
    description: "Upscale 3-7BR villas around lakes. Premium over Springs for privacy and plot sizes. Strong end-user demand; limited supply.",
  },
  {
    slug: "the-lakes",
    name: "The Lakes",
    tier: "priority",
    propertyTypes: ["Villa"],
    developer: "Emaar",
    handover: "2005-2009",
    avgPricePerSqft: 1550,
    avgYield: 5.0,
    minPrice: 4800000,
    maxPrice: 18000000,
    amenities: ["Central Park", "Lakes", "Club", "Retail centre"],
    description: "Mediterranean-style 3-5BR villas. Quieter than Meadows, good plot ratios, steady appreciation.",
  },
  {
    slug: "emirates-hills",
    name: "Emirates Hills",
    tier: "priority",
    propertyTypes: ["Villa"],
    developer: "Emaar",
    handover: "2003-2010",
    avgPricePerSqft: 2400,
    avgYield: 3.2,
    minPrice: 18000000,
    maxPrice: 250000000,
    amenities: ["Montgomerie Golf", "24/7 security", "Custom mansions", "Lakeside plots"],
    description: "Dubai's Beverly Hills. Custom-built 5-10BR mansions on golf course. Ultra-prime: capital appreciation play, lower yields, trophy asset.",
  },
  {
    slug: "the-views",
    name: "The Views",
    tier: "premium",
    propertyTypes: ["Apartment", "Townhouse"],
    developer: "Emaar",
    handover: "2006-2008",
    avgPricePerSqft: 1750,
    avgYield: 6.0,
    minPrice: 1600000,
    maxPrice: 12000000,
    amenities: ["Montgomerie Golf views", "Pools", "Gyms", "Walking paths"],
    description: "Golf-course-facing apartments and townhouses. Good yields for Emirates Living investors seeking lower entry point.",
  },

  // ===== PRIORITY: Jumeirah Park =====
  {
    slug: "jumeirah-park",
    name: "Jumeirah Park",
    tier: "priority",
    propertyTypes: ["Villa"],
    developer: "Nakheel",
    handover: "2012-2016",
    avgPricePerSqft: 1500,
    avgYield: 5.5,
    minPrice: 4500000,
    maxPrice: 14000000,
    amenities: ["Pavilion retail", "Schools", "Parks", "Community pools"],
    description: "Gated villa community west of SZR. 3-5BR Legacy, Regional, Heritage styles. Strong end-user demand, close to Metro and JLT.",
  },

  // ===== PRIORITY: Arabian Ranches =====
  {
    slug: "arabian-ranches",
    name: "Arabian Ranches",
    tier: "priority",
    propertyTypes: ["Villa"],
    developer: "Emaar",
    handover: "2004-2008",
    avgPricePerSqft: 1350,
    avgYield: 5.5,
    minPrice: 3200000,
    maxPrice: 15000000,
    amenities: ["Golf Club", "Polo Club", "Ranches Souk", "Schools", "Horse riding"],
    description: "Established desert-themed villa community. 10+ sub-communities (Saheel, Alvorada, Mirador, etc.). Strong rental demand from families.",
  },
  {
    slug: "arabian-ranches-2",
    name: "Arabian Ranches II",
    tier: "priority",
    propertyTypes: ["Villa"],
    developer: "Emaar",
    handover: "2015-2018",
    avgPricePerSqft: 1450,
    avgYield: 5.3,
    minPrice: 3800000,
    maxPrice: 18000000,
    amenities: ["Central park", "Pool", "Schools", "Retail plaza"],
    description: "Newer phase with Lila, Samara, Palma, Rosa, Azalea sub-communities. Modern Spanish/Mediterranean villas.",
  },
  {
    slug: "arabian-ranches-3",
    name: "Arabian Ranches III",
    tier: "priority",
    propertyTypes: ["Villa", "Townhouse"],
    developer: "Emaar",
    handover: "2022-2024",
    avgPricePerSqft: 1550,
    avgYield: 5.8,
    minPrice: 2900000,
    maxPrice: 9500000,
    amenities: ["Lazy river", "Central park", "Retail", "Schools under construction"],
    description: "Newest Ranches phase. Sun, Joy, Bliss, Ruba sub-communities. 3-5BR townhouses and villas, modern designs.",
  },

  // ===== PREMIUM: Other Top Villa Communities =====
  {
    slug: "palm-jumeirah",
    name: "Palm Jumeirah",
    tier: "premium",
    propertyTypes: ["Villa", "Apartment", "Penthouse"],
    developer: "Nakheel",
    handover: "2007+",
    avgPricePerSqft: 3200,
    avgYield: 4.5,
    minPrice: 12000000,
    maxPrice: 400000000,
    amenities: ["Private beach", "Nakheel Mall", "Atlantis", "View Point"],
    description: "Iconic man-made island. Frond villas, signature villas, garden homes. Beachfront luxury, strong short-let yields.",
  },
  {
    slug: "damac-hills",
    name: "DAMAC Hills",
    tier: "premium",
    propertyTypes: ["Villa", "Townhouse", "Apartment"],
    developer: "DAMAC",
    handover: "2017-2021",
    avgPricePerSqft: 1100,
    avgYield: 6.2,
    minPrice: 2200000,
    maxPrice: 35000000,
    amenities: ["Trump International Golf", "Park", "Retail", "Schools"],
    description: "Golf-themed community, great yield play for investors. Villas at competitive PSF vs established areas.",
  },
  {
    slug: "dubai-hills-estate",
    name: "Dubai Hills Estate",
    tier: "premium",
    propertyTypes: ["Villa", "Townhouse", "Apartment"],
    developer: "Emaar",
    handover: "2019-2024",
    avgPricePerSqft: 1850,
    avgYield: 5.0,
    minPrice: 2800000,
    maxPrice: 80000000,
    amenities: ["Dubai Hills Mall", "Golf course", "Park", "Metro planned"],
    description: "Master-planned community between DT and Marina. Fairways, Golf Place, Parkways. Rapid appreciation since launch.",
  },
  {
    slug: "tilal-al-ghaf",
    name: "Tilal Al Ghaf",
    tier: "premium",
    propertyTypes: ["Villa", "Townhouse"],
    developer: "Majid Al Futtaim",
    handover: "2022-2026",
    avgPricePerSqft: 1900,
    avgYield: 5.2,
    minPrice: 2400000,
    maxPrice: 120000000,
    amenities: ["Crystal Lagoon beach", "Park", "School", "Retail"],
    description: "Lagoon community with Harmony, Aura, Elan, Serenity. Strong capital appreciation, lifestyle-driven.",
  },
  {
    slug: "the-valley",
    name: "The Valley",
    tier: "standard",
    propertyTypes: ["Villa", "Townhouse"],
    developer: "Emaar",
    handover: "2022-2025",
    avgPricePerSqft: 1050,
    avgYield: 6.5,
    minPrice: 1900000,
    maxPrice: 5500000,
    amenities: ["Golden Beach", "Sports village", "Town centre", "Schools planned"],
    description: "Emaar's affordable villa community on Al Ain road. Entry-level 3-4BR for families and investors.",
  },
  {
    slug: "mudon",
    name: "Mudon",
    tier: "standard",
    propertyTypes: ["Villa", "Townhouse"],
    developer: "Dubai Properties",
    handover: "2015-2019",
    avgPricePerSqft: 1200,
    avgYield: 6.0,
    minPrice: 2100000,
    maxPrice: 8500000,
    amenities: ["Central park", "Retail", "Schools", "Sports courts"],
    description: "Spanish/Moroccan themed villas on Emirates Road. Good yield, affordable family community.",
  },
  {
    slug: "reem-mira",
    name: "Mira (Reem)",
    tier: "standard",
    propertyTypes: ["Townhouse"],
    developer: "Emaar",
    handover: "2015-2018",
    avgPricePerSqft: 1250,
    avgYield: 6.2,
    minPrice: 2200000,
    maxPrice: 4800000,
    amenities: ["Community pool", "Park", "Retail nearby"],
    description: "Affordable 3-4BR townhouses in Reem community. Strong rental demand from young families.",
  },
  {
    slug: "jumeirah-village-circle",
    name: "Jumeirah Village Circle",
    tier: "standard",
    propertyTypes: ["Villa", "Townhouse", "Apartment"],
    developer: "Nakheel",
    handover: "2013+",
    avgPricePerSqft: 1100,
    avgYield: 7.2,
    minPrice: 1500000,
    maxPrice: 9000000,
    amenities: ["Circle Mall", "Parks", "Schools", "Mosques"],
    description: "High-yield mixed community. Affordable villas and townhouses. Strong investor appetite for short-let.",
  },
  {
    slug: "al-furjan",
    name: "Al Furjan",
    tier: "standard",
    propertyTypes: ["Villa", "Townhouse", "Apartment"],
    developer: "Nakheel",
    handover: "2013+",
    avgPricePerSqft: 1150,
    avgYield: 6.5,
    minPrice: 2000000,
    maxPrice: 7500000,
    amenities: ["Metro", "Pavilion retail", "Schools", "Pools"],
    description: "Metro-served villa community near Expo City and JLT. Quatro, Dubai Style, Murano clusters.",
  },
  {
    slug: "nad-al-sheba-gardens",
    name: "Nad Al Sheba Gardens",
    tier: "premium",
    propertyTypes: ["Villa"],
    developer: "Meraas",
    handover: "2024-2026",
    avgPricePerSqft: 2100,
    avgYield: 4.8,
    minPrice: 5500000,
    maxPrice: 45000000,
    amenities: ["Park", "Schools", "Lagoon", "Equestrian"],
    description: "Low-density premium villa enclave near Meydan. Contemporary design, sought-after by HNW end-users.",
  },
];

export const PRIORITY_COMMUNITIES = SEED_COMMUNITIES.filter(c => c.tier === "priority").map(c => c.slug);
