-- Elite Broker OS — Demo Campaign Seed
-- Paste this entire file into your Supabase SQL Editor and click Run.

CREATE TABLE IF NOT EXISTS campaigns (
  id            TEXT PRIMARY KEY,
  name          TEXT,
  phone         TEXT,
  phone2        TEXT,
  phone3        TEXT,
  email         TEXT,
  type          TEXT,
  stage         TEXT,
  urgency       TEXT,
  community     TEXT,
  sub_comm      TEXT,
  property      TEXT,
  full_address  TEXT,
  plot_number   TEXT,
  dld_num       TEXT,
  permit_num    TEXT,
  bedrooms      TEXT,
  bathrooms     TEXT,
  prop_type     TEXT,
  area          TEXT,
  vacancy       TEXT,
  asking_price  TEXT,
  market_val    TEXT,
  budget_min    TEXT,
  budget_max    TEXT,
  wa_msg        TEXT,
  sent          BOOLEAN DEFAULT false,
  last_sent_date TEXT,
  follow_ups    INTEGER DEFAULT 0,
  nationality   TEXT,
  motivation    TEXT,
  source        TEXT,
  notes         TEXT,
  added_at      BIGINT
);

-- 4 demo contacts (INSERT OR IGNORE so re-running is safe)
INSERT INTO campaigns
  (id, name, phone, email, type, stage, urgency, community, sub_comm, property, bedrooms, prop_type, area, asking_price, market_val, nationality, motivation, source, notes, sent, added_at)
VALUES
  (
    'camp_demo_001',
    'Ahmed Al Mansoori',
    '971501234567',
    'ahmed.mansoori@email.com',
    'Seller',
    'New',
    'Hot',
    'Arabian Ranches',
    'Saheel',
    'Villa 14, Saheel 3',
    '5',
    'Villa',
    '5800',
    '4200000',
    '4350000',
    'Emirati',
    'Upgrading to larger property',
    'DLD Data',
    'Owner since 2015. Motivated to sell within 3 months.',
    false,
    1743552000000
  ),
  (
    'camp_demo_002',
    'Priya Sharma',
    '971509876543',
    'priya.sharma@email.com',
    'Investor',
    'Contacted',
    'Warm',
    'Downtown Dubai',
    'Burj Residences',
    'Apt 2204, Tower 3',
    '2',
    'Apartment',
    '1450',
    '1850000',
    '1920000',
    'Indian',
    'Portfolio diversification',
    'Referral',
    'Looking for high-ROI units. Flexible on closing date.',
    false,
    1743552000000
  ),
  (
    'camp_demo_003',
    'James Harrison',
    '971554441122',
    'james.harrison@email.com',
    'Buyer',
    'Qualified',
    'Hot',
    'Palm Jumeirah',
    'Signature Villas',
    'Frond G, Villa 23',
    '3',
    'Villa',
    '4200',
    '6500000',
    '6750000',
    'British',
    'Primary residence — relocating family from London',
    'Website Inquiry',
    'Pre-approved mortgage. Wants sea-facing unit. Target move-in Q3 2026.',
    false,
    1743552000000
  ),
  (
    'camp_demo_004',
    'Fatima Al Rashidi',
    '971506667788',
    'fatima.rashidi@email.com',
    'Landlord',
    'Viewing Scheduled',
    'Warm',
    'Jumeirah Village Circle',
    'District 10',
    'Apt 507, The Myth',
    '1',
    'Apartment',
    '780',
    '850000',
    '870000',
    'Emirati',
    'Selling to reinvest in commercial property',
    'Cold Call',
    'Currently tenanted — lease expires June 2026. Happy to sell with tenant.',
    false,
    1743552000000
  )
ON CONFLICT (id) DO NOTHING;
